language: php

php:
  - 7.4.0
  - 7.4.1
  - 7.4

matrix:
  include:
    - php: 7.4
      env:
        - xdebug=yes
    - php: 7.4
      env:
        - psalm=yes
    - php: 7.4
      env:
        - xdebug=yes
        - infection=yes
  fast_finish: true

cache:
  files:
    - ./.php_cs.cache
    - /.phpunit.result.cache
  directories:
    - $HOME/.composer/cache
    - ./psalm/cache

before_script:
  - if [[ "$xdebug" != "yes" || "$psalm" = "yes" ]]; then phpenv config-rm xdebug.ini; fi

install:
  - travis_retry composer install --no-interaction --no-suggest --prefer-dist

script:
  - if [[ "$psalm" != "yes" && "$xdebug" != "yes" ]]; then composer run static-analysis; fi
  - if [[ "$psalm" = "yes" ]]; then vendor/bin/psalm --show-info=false --diff --diff-methods; fi
  - if [[ "$xdebug" = "yes" && "$infection" != "yes" ]]; then vendor/bin/phpunit --prepend=./phpunit.xdebug-filter.php --coverage-clover ./phpunit.clover && vendor/bin/php-coveralls -v; fi
  - if [[ "$infection" = "yes" ]]; then ./vendor/bin/phpunit  --prepend=./phpunit.xdebug-filter.php --coverage-xml=./coverage/coverage-xml/ --log-junit=./coverage/junit.xml; fi
  - if [[ "$infection" = "yes" ]]; then phpenv config-rm xdebug.ini && ./vendor/bin/infection --coverage=./coverage/ -j$(nproc); fi

after_script:
  - if [[ "$infection" = "yes" ]]; then cat infection.log; fi
